name: golangci-lint
on:
  push:
    paths:
      - 'src/*.go'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        run: docker run -v "$PWD:/src" rymiyamoto/reserva-go-docker:latest /bin/sh -c "go mod download && golangci-lint run"
        working-directory: src

